# basic options
title: Public depository for Covid-19 outbreak in Lamezia Terme
author: Giovanni Nicolazzo
email: nicolazzo.giovanni@outlook.it
description: Public depository for Covid-19 outbreak in Lamezia Terme
twitter_username: giovannicolaz_
github_username:  colazeta

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
