# basic options
title: Panoramica sul contagio
author: Giovanni Nicolazzo
email: nicolazzo.giovanni@outlook.it
description: Il portale desidera offrire informazioni aggiornate sull'evoluzione del contagio da SARS-Cov-2 in Calabria, reperendo informazioni da fonti istituzionali, locali e private.
twitter_username: giovannicolaz_
github_username:  colazeta

# Build settings
markdown: kramdown
theme: minima
