# basic options
title: Panoramica sul contagio
author: Giovanni Nicolazzo
email: nicolazzo.giovanni@outlook.it
description: 
twitter_username: giovannicolaz_
github_username:  colazeta

# Build settings
markdown: kramdown
theme: minima
